#!/bin/sh
#This config is intended for use with braidstag
ip link add name mesh-bridge type bridge
ip link set dev eth0 master mesh-bridge
ip link set dev bat0 master mesh-bridge
ip link set up dev mesh-bridge
#ip addr add 192.168.0.231/24 dev mesh-bridge
