#!/bin/sh
#This config is intended for use with braidstag - static mode
ip link add name mesh-bridge type bridge
ip link set dev eth0 master mesh-bridge
ip link set dev bat0 master mesh-bridge
ip link set up dev mesh-bridge
ip addr add {{ staticip }}/24 dev mesh-bridge
route add default gw {{ staticgateway }}
sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
