---
- hosts: gateways
  become: true

  tasks:
#  - name: Ensure screen is installed
#    apt: name=screen state=installed

  - name: Ensure batctl is installed
    apt: name=batctl state=present

  - name: DHCPCD files
    template: src=templates/dhcpcdstatic.conf dest=/etc/dhcpcd.conf
    notify: reboot sequence
  - name: Interfaces files
    template: src=templates/interfaces  dest=/etc/network/interfaces
    notify: reboot sequence
  - name: WPA_Supplicant file
    template: src=templates/wpa_supplicant.tmplt  dest=/etc/wpa_supplicant/wpa_supplicant.conf
    notify: reboot sequence
  - name: Bridge file
    template: src=templates/bridgestatic2      dest=/home/pi/bridge  mode=+x
    notify: reboot sequence


  - name: Copy debug file from template
    template: src=templates/debug        dest=/home/pi/debug

  handlers:
    - name: reboot sequence
      changed_when: "true"
      debug: msg='trigger machine reboot sequence'
      notify:
        - get current time
        - reboot system
        - waiting for server to come back
    - name: get current time
      command: /bin/date +%s
      register: before_reboot
      become: false
    - name: reboot system
      shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
    - name: waiting for server to come back
      wait_for_connection:
        delay: 30

- hosts: guns
  become: true

  tasks:
#  - name: Ensure screen is installed
#    apt: name=screen state=present

  - name: Ensure batctl is installed
    apt: name=batctl state=present

  - name: Set hostname to match inventory hostname in /hosts
    lineinfile:
                  path: /etc/hosts
                  regexp: '^127.0.1.1'
                  line: '127.0.1.1  {{ inventory_hostname }}'
    become: true
    notify: reboot sequence

  - name: DHCPCD files
    template: src=templates/dhcpcdstatic.conf dest=/etc/dhcpcd.conf
    notify: reboot sequence
  - name: Interfaces files
    template: src=templates/interfaces  dest=/etc/network/interfaces
    notify: reboot sequence
  - name: WPA_Supplicant file
    template: src=templates/wpa_supplicant.tmplt  dest=/etc/wpa_supplicant/wpa_supplicant.conf
    notify: reboot sequence
  - name: Bridge file
    template: src=templates/bridgestatic2      dest=/home/pi/bridge  mode=+x
    notify: reboot sequence


  - name: Copy debug file from template
    template: src=templates/debug        dest=/home/pi/debug

#  - include: gamesetup.yml

  handlers:
    - name: reboot sequence
      changed_when: "true"
      debug: msg='trigger machine reboot sequence'
      notify:
        - get current time
        - reboot system
        - waiting for server to come back
    - name: get current time
      command: /bin/date +%s
      register: before_reboot
      become: false
    - name: reboot system
      shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
    - name: waiting for server to come back
      wait_for_connection:
        delay: 30
