- hosts: all
  gather_facts: False
  vars_prompt:
    - name: "Version"
      prompt: "Choose a hostname"
      private: no

  tasks:
    - replace:
        path: /boot/cmdline.txt
        regexp: 'console=serial0,115200 '
      become: true
