- hosts: all
  gather_facts: False
  vars_prompt:
    - name: "Version"
      prompt: "Choose a hostname"
      private: no

  tasks:
    - name: Ansible prompt example.
      debug:
        msg: "{{ Version }}"
