- name: Verify dependancies for game
  apt:
    name:
     - python
     - python-serial
     - python-pyside.qtgui
     - python-pyside.qtxml
     - git
     - screen     
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Get game software
  git:
    repo: '{{ game_repo }}'
    dest: ~/braidstag/arduino-milestag/
    version: '{{ game_version }}'
    force: yes

- name: Verify/install systemd service
  template:
    src: templates/systemd/braidstag.service
    dest: /lib/systemd/system/braidstag.service
  become: true

- name: Ensure systemd service is enabled
  systemd:
    name: braidstag
    enabled: yes
  become: true
