- name: reboot sequence
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - get current time
    - reboot system
    - waiting for server to come back

- name: get current time
  command: /bin/date +%s
  register: before_reboot
  become: false

- name: reboot system
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: true

- name: waiting for server to come back
  wait_for_connection:
    delay: 30
