#!/bin/sh
#This config is intended for use with braidstag
ip link add name mesh-bridge type bridge
ip link set dev eth0 master mesh-bridge
ip link set dev bat0 master mesh-bridge
ip link set up dev mesh-bridge

#if we have a static ip and are setup to use static allocation
{% if use_static_ips %}
ip addr add {{ staticip }}/24 dev mesh-bridge
route add default gw {{ staticgateway }}
sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
{% endif %}
