- pause:
    prompt: "Enter path if using your own firmware build. Leave blank to use whatever is onboard. -- You must run gamesetup role to revert firmware --"
  register: pause_result
  run_once: True	
- name: Copy development hex file
  copy:
   src: "{{ pause_result.user_input }}"
   dest: /home/pi/braidstag/arduino-milestag/hex/IRcomms.ino.with_bootloader.hex
  when: pause_result.user_input|length

- name: Verify dependancies
  apt:
    name:
     - avrdude
     - wiringpi
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Create target directory
  file:
    path: /home/pi/braidstag/config
    state: directory

- name: Verify AVRDUDE Configuration
  template:
    src: templates/avrdude_gpio.conf
    dest: /home/pi/braidstag/config/avrdude_gpio.conf

- name: Verify flashing script
  template:
    src: templates/flash.sh
    dest: /home/pi/braidstag/config/flash.sh
    mode: "a=rwx"

- name: Flash
  shell: /home/pi/braidstag/config/flash.sh
  become: true
